const Actions = {
  SEARCH_PLAYER_START: 'SEARCH_PLAYER_START',
  SEARCH_PLAYER_SUCCEED: 'SEARCH_PLAYER_SUCCEED',
  SEARCH_PLAYER_FAIL: 'SEARCH_PLAYER_FAIL',
  LOAD_PLAYER_START: 'LOAD_PLAYER_START',
  LOAD_PLAYER_SUCCEED: 'LOAD_PLAYER_SUCCEED',
  LOAD_PLAYER_FAIL: 'LOAD_PLAYER_FAIL',
  LOAD_GENERAL_START: 'LOAD_GENERAL_START',
  LOAD_GENERAL_SUCCEED: 'LOAD_GENERAL_SUCCEED',
  LOAD_GENERAL_FAIL: 'LOAD_GENERAl_FAIL',
  SORT_WEAPON_STATS: 'SORT_WEAPON_STATS'
};

export default Actions;
